crm_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("customers.urls")),
    path('', include("equipment.urls")),
    path("accounts/", include("django.contrib.auth.urls")), 
]

customers/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from . import views
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'customers'

urlpatterns = [
    path('', login_required(views.CustomerView.as_view()), name='customers'),
    path('customers', login_required(views.CustomerView.as_view()), name='customers'),
    path('add/', login_required(views.AddCustomerView.as_view()), name='add_customer'),
    path('edit/<int:pk>/', login_required(views.EditCustomerView.as_view()), name='edit_customer'),
    path('edit_address/<int:pk>/', login_required(views.EditAddressView.as_view()), name='edit_address'),
    path('delete/<int:pk>/', login_required(views.DeleteCustomerView.as_view()), name='delete_customer'),
    path('view/<int:pk>/', login_required(views.CustomerDetailView.as_view()), name='customer_detail'),
    path('search_customers', views.search_customers, name='search_customers'),
    path('search_results', views.search, name='search_results'),

]

equipment/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'equipment'

urlpatterns = [
    path('equipment', login_required(views.EquipmetView.as_view()), name='equipment'),
    path('add_equipment/<int:customer_id>', views.AddEquipmentView.as_view(), name='add_equipment'), 
]

customers/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)

    customer_type = models.CharField(max_length=100, 
                                     choices=[('Individual', 'Individual'), ('Organization', 'Organization')], 
                                     default='Individual',
                                     blank=False)

    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)

    organization_name = models.CharField(max_length=100, blank=True)
    organization_registration_number = models.CharField(max_length=100, blank=True)
    organization_vat_number = models.CharField(max_length=100, blank=True)

    email = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=100, blank=False, unique=True)
    
    address = models.ForeignKey("Address", related_name='customer_addresses', on_delete=models.PROTECT)
    
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.customer_type == 'Organization':
            return f"{self.organization_name} {self.address}"
        return f"{self.first_name} {self.last_name} {self.address}"


class Address(models.Model):
    address_id = models.AutoField(primary_key=True)

    street_name = models.CharField(max_length=100, blank=True)
    street_number = models.CharField(max_length=100, blank=True)
    postal_code = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    county = models.CharField(max_length=100, blank=True)
    neighborhood = models.CharField(max_length=100, blank=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.street_name} {self.street_number} {self.city}"

customers/forms.py
from django import forms
from .models import Address, Customer
from betterforms.multiform import MultiModelForm


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = '__all__'


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['customer_type', 
                  'first_name', 
                  'last_name', 
                  'organization_name', 
                  'organization_registration_number', 
                  'organization_vat_number', 
                  'email', 
                  'phone']
        

class CustomerMultiForm(MultiModelForm):
    
    form_classes = {
        'customer': CustomerForm,
        'address': AddressForm,
    }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
     
        

customers/views.py
from typing import Any, Dict
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, View
from .models import Customer, Address
from equipment.models import Equipment
from .forms import CustomerMultiForm, AddressForm, CustomerForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required


class CustomerView(ListView):
    model = Customer
    template_name = 'customers/customers.html'
    context_object_name = 'customers'
    ordering = ['-date_modified']
    paginate_by = 10

class CustomerDetailView(DetailView):
    model = Customer
    template_name = 'customers/customer_detail.html'
    context_object_name = 'customer'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['equipment'] = Equipment.objects.filter(customer=self.object)
        return context

class AddCustomerView(CreateView):
    form_class = CustomerMultiForm
    success_url = '/customers'
    template_name = 'customers/add_customer.html'

    def form_valid(self, form):
        address = form['address'].save()
        customer = form['customer'].save(commit=False)
        customer.address = address
        customer.save()
        return redirect(self.success_url)

class EditCustomerView(UpdateView):
    model = Customer
    fields = [
        'customer_type', 'first_name', 'last_name', 'organization_name', 'organization_registration_number', 
        'organization_vat_number', 'email', 'phone']
    success_url = '/customers'
    template_name = 'customers/edit_customer.html'

class EditAddressView(UpdateView):
    model = Address
    fields = "__all__"
    success_url = '/customers'
    template_name = 'customers/edit_address.html'

class DeleteCustomerView(DeleteView):
    model = Customer
    success_url = '/customers'
    template_name = 'customers/delete_customer.html'
    context_object_name = 'customer'


@login_required
def search_customers(request):
    return render(request, 'customers/search_customers.html')


@login_required
def search(request):
    search_term = request.POST.get('search', None)
    if search_term:
        results = Customer.objects.filter(
            Q(first_name__icontains=search_term) | 
            Q(last_name__icontains=search_term) | 
            Q(address__street_name__icontains=search_term) | 
            Q(email__icontains=search_term) | 
            Q(organization_name__icontains=search_term)
            )
              
        context = {'results': results}
    else:
        context = {}
    return render(request, 'customers/search_results.html', context)

customers/templates/customers/add_customer.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="row justify-content-left mt-5">
      <div class="col-lg-4 col-md-6 col-sm-6">
          <div class="card-title text-center border-bottom">
            <h2 class="p-3">Add Customer</h2>
          </div>
          <div class="card-body">
              <div class="mb-4">

                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                
                </div>
                  <div class="mb-4">
                          <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>

</div>
</div>
</div>
</div>
</div>
{% endblock %}

customers/templates/customers/customer_detail.html
{% extends "base.html" %}
{% block content %}

<h3>
{% if customer.customer_type == "Organization" %}
    {{ customer.organization_name }}
{% elif customer.first_name|length == 0 and  customer.last_name|length == 0 %}
    {{ customer.address }}
{% else %}
    {{ customer.first_name }} {{ customer.last_name }}
{% endif %}
</h3>
<ul class="list-unstyled">
{% if customer.organization_registration_number|length > 0 %}
<li>{{ customer.organization_registration_number }}</li>
{% endif %}
<li>{{ customer.email }}</li>
<li>{{ customer.address }}</li>

<li>{{ customer.phone }}</li>
</ul>
<hr />
<ul class="list-unstyled">
    <li><small>Created: {{ customer.date_created }}</small></li>
    <li><small>Modified: {{ customer.date_modified }}</small></li>
</ul>



<hr/>

<p><a href="{% url 'equipment:add_equipment' customer.customer_id %}">Add Equipment</a></p>

<p><a href="{% url 'customers:edit_customer' customer.customer_id %}">Edit Customer Details</a></p>
<p><a href="{% url 'customers:edit_address' customer.address_id %}">Edit Address</a></p>
<p><a href="{% url 'customers:delete_customer' customer.customer_id %}">Delete</a></p>

<hr />
{% include 'equipment/equipment_list.html' %}

{% endblock %}

customers/templates/customers/customers.html
{% extends "base.html" %}
{% block content %}

<div class="container">
<h2>Customers</h2>

<table class="table table-sm">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Address</th>
        <th></th>
   
    </tr>
    {% for customer in customers %}
    <tr>
        <td>{{ customer.customer_id }}</td>
        <td>
            {% if customer.customer_type == "Organization" %}
                {{ customer.organization_name }}
            {% elif customer.first_name|length == 0 and  customer.last_name|length == 0 %}
                {{ customer.address }}
            {% else %}
                {{ customer.first_name }} {{ customer.last_name }}
            {% endif %}
        </td>
        <td>{{ customer.email }}</td>
        <td>{{ customer.phone }}</td>
        <td>{{ customer.address }}</td>
        <td><a href="{% url 'customers:customer_detail'  customer.customer_id %}">View</a></td>
        </tr>
    {% endfor %}


</div>
{% endblock %}

customers/templates/customers/delete_customer.html
{% extends "base.html" %}
{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ customer.first_name }} @ {{ customer.address }}"?</p>
    <a href="{{ view.get_success_url }}" class="btn btn-primary">Cancel</a>
    <input type="submit" value="Confirm" class="btn btn-danger">
 </form>

{% endblock %}

customers/templates/customers/edit_address.html
{% extends "base.html" %}
{% block content %}
{% load widget_tweaks %}



<div class="container">
    <div class="row justify-content-left mt-5">
      <div class="col-lg-4 col-md-6 col-sm-6">
          <div class="card-title text-center border-bottom">
            <h2 class="p-3">Edit Address</h2>
          </div>
          <div class="card-body">

<form method="POST">

    {% csrf_token %}
    {{ form.errors }}
    {{ form.non_field_errors }}

    <div class="mb-4">
    {{ form.street_name.label }}
    {% render_field form.street_name class="form-control" %}

    
    {{ form.street_number.label }}
    {% render_field form.street_number class="form-control" %}

    {{ form.city.label }}
    {% render_field form.city class="form-control" %}

    {{ form.county.label }}
    {% render_field form.county class="form-control" %}

    {{ form.neighborhood.label }}
    {% render_field form.neighborhood  class="form-control" %}

    {{ form.postal_code.label }}
    {% render_field form.postal_code class="form-control" %}
    </div>


<input type="submit" value="Update Address" class="btn btn-primary" /> 
</form>
            
</form>
</div>
</div>
</div>
</div>
</div>

{% endblock %}

customers/templates/customers/edit_customer.html
{% extends "base.html" %}
{% block content %}
{% load widget_tweaks %}



<div class="container">
    <div class="row justify-content-left mt-5">
      <div class="col-lg-4 col-md-6 col-sm-6">
          <div class="card-title text-center border-bottom">
            <h2 class="p-3">Edit Customer</h2>
          </div>
          <div class="card-body">

<form method="POST">

    {% csrf_token %}
    {{ form.errors }}
    {{ form.non_field_errors }}
    
    <div class="mb-4">
    {{ form.customer_type.label }}
    {% render_field form.customer_type class="form-control" %}


    {{ form.first_name.label }}
    {% render_field form.first_name class="form-control" %}


    {{ form.last_name.label }}
    {% render_field form.last_name class="form-control" %}

    {{ form.organization_name.label }}
    {% render_field form.organization_name class="form-control" %}

    {{ form.organization_registration_number.label }}
    {% render_field form.organization_registration_number class="form-control" %}
 
    {{ form.organization_vat_number.label }}
    {% render_field form.organization_vat_number class="form-control" %}
    {{ form.phone.label }}
    {% render_field form.phone class="form-control" %}
    {{ form.email.label }}
    {% render_field form.email class="form-control" %}
    </div>

    



<input type="submit" value="Update Customer" class="btn btn-primary" /> 
</form>
            
</form>
</div>
</div>
</div>
</div>
</div>

{% endblock %}

customers/templates/customers/search_customers.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <br>
        <section>
                <form>
                    {% csrf_token %}
                    <input 
                    type="search" 
                    
                    hx-post="{% url 'customers:search_results' %}" 
                    hx-target='#results'
                    hx-trigger="keyup changed delay:500ms, search" 
                    
                    name="search" 
                    class="form-control-sm mr-2"
                    placeholder="Search customers..." />
                </form>
            </section>
            <div id="results">
            
            </div>
 
</div>

{% endblock %}

customers/templates/customers/search_results.html
{% if results %}
    {% csrf_token %}
    <ul>
    {% for customer in results %}
        <li>
            <a href="{% url 'customers:customer_detail'  customer.customer_id %}">{{ customer }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No search results</p>
{% endif %}



{% comment %} 
<span class="badge badge-success badge-pill" 
style="cursor: pointer;"
hx-post="{% url 'add-film' %}"
hx-vals='{"filmname": "{{film.name}}"}'
hx-target="#film-list">add</span> 
{% endcomment %}