crm_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("customers.urls")),
    path('', include("equipment.urls")),
    path("accounts/", include("django.contrib.auth.urls")), 
]

customers/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from . import views
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'customers'

urlpatterns = [
    path('', login_required(views.CustomerView.as_view()), name='customers'),
    path('customers', login_required(views.CustomerView.as_view()), name='customers'),
    path('add/', login_required(views.AddCustomerView.as_view()), name='add_customer'),
    path('edit/<int:pk>/', login_required(views.EditCustomerView.as_view()), name='edit_customer'),
    path('edit_address/<int:pk>/', login_required(views.EditAddressView.as_view()), name='edit_address'),
    path('delete/<int:pk>/', login_required(views.DeleteCustomerView.as_view()), name='delete_customer'),
    path('view/<int:pk>/', login_required(views.CustomerDetailView.as_view()), name='customer_detail'),
    path('search_customers', views.search_customers, name='search_customers'),
    path('search_results', views.search, name='search_results'),

]

equipment/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'equipment'

urlpatterns = [
    path('equipment', login_required(views.EquipmetView.as_view()), name='equipment'),
    path('add_equipment/<int:customer_id>', views.AddEquipmentView.as_view(), name='add_equipment'), 
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>HVAC CRM</title>
    {% endblock %} 
    {% load bootstrap5 %} 
    {% bootstrap_css %} 
    {%  bootstrap_javascript %} 
    {% bootstrap_messages %}
    <script src="https://unpkg.com/htmx.org@1.8.0"></script>
  </head>


    <body>

    <div class="container">

      <hr />

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="">CRM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="">Jobs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customers:customers' %}">Customers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customers:add_customer' %}">Add Customer</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customers:search_customers' %}">Search</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'equipment:equipment' %}">Equipment</a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>

          </ul>
        </div>
      </nav> 

      {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %} 
      {% block content %}<!-- default content text (typically empty) -->{% endblock %}
    </div>
  </body>
</html>